server:
  port: 8082
spring:
  application:
    name: ussd-api
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5435/ussd
    username: postgres
    hikari:
      maxLifetime: '1800000'
      connectionTimeout: '30000'
      idleTimeout: '600000'
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


africaTalking:
  smsUrl:  https://api.sandbox.africastalking.com/version1/messaging?
  apiKey: 5e6e58517e029b3e0770351459a3cbc8103fce9ea770c285d95513815226511b
  username: sandbox